{
    "139.99.156.154:6934": {
        "login": "default-login",
        "password": "xmq7llbppj8wnpjuk2233bmr10dmdcw",
        "publicKey": "jvkvn5cv15dlpgb36t5hf4bsr7vwwsvug3n711f964wwruyxfnn0.k",
        "peerName": "davo"
    },
    "[2402:1f00:8100:400::9f]:6934": {
        "login": "default-login",
        "password": "xmq7llbppj8wnpjuk2233bmr10dmdcw",
        "publicKey": "jvkvn5cv15dlpgb36t5hf4bsr7vwwsvug3n711f964wwruyxfnn0.k",
        "peerName": "davo"
    }
}
